<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2016-03-03T03:34:07+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.access_entity_updated
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'site' => 'zeus',
    'version_installed' => '5.7.5.6',
    'misc' => array(
        'access_entity_updated' => 1456976047,
    ),
);
